// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: glp.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGlpAssetsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetGlpAssetsRequest) Reset() {
	*x = GetGlpAssetsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_glp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGlpAssetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlpAssetsRequest) ProtoMessage() {}

func (x *GetGlpAssetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_glp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlpAssetsRequest.ProtoReflect.Descriptor instead.
func (*GetGlpAssetsRequest) Descriptor() ([]byte, []int) {
	return file_glp_proto_rawDescGZIP(), []int{0}
}

type GetGlpAssetsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Assets []*GlpAsset `protobuf:"bytes,1,rep,name=assets,proto3" json:"assets,omitempty"`
}

func (x *GetGlpAssetsResponse) Reset() {
	*x = GetGlpAssetsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_glp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetGlpAssetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGlpAssetsResponse) ProtoMessage() {}

func (x *GetGlpAssetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_glp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGlpAssetsResponse.ProtoReflect.Descriptor instead.
func (*GetGlpAssetsResponse) Descriptor() ([]byte, []int) {
	return file_glp_proto_rawDescGZIP(), []int{1}
}

func (x *GetGlpAssetsResponse) GetAssets() []*GlpAsset {
	if x != nil {
		return x.Assets
	}
	return nil
}

type GlpAsset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol     string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	PoolAmount []byte `protobuf:"bytes,2,opt,name=poolAmount,proto3" json:"poolAmount,omitempty"`
	Weight     []byte `protobuf:"bytes,3,opt,name=weight,proto3" json:"weight,omitempty"`
	UsdgAmount []byte `protobuf:"bytes,4,opt,name=usdgAmount,proto3" json:"usdgAmount,omitempty"`
	Allocation []byte `protobuf:"bytes,5,opt,name=allocation,proto3" json:"allocation,omitempty"`
}

func (x *GlpAsset) Reset() {
	*x = GlpAsset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_glp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlpAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlpAsset) ProtoMessage() {}

func (x *GlpAsset) ProtoReflect() protoreflect.Message {
	mi := &file_glp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlpAsset.ProtoReflect.Descriptor instead.
func (*GlpAsset) Descriptor() ([]byte, []int) {
	return file_glp_proto_rawDescGZIP(), []int{2}
}

func (x *GlpAsset) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GlpAsset) GetPoolAmount() []byte {
	if x != nil {
		return x.PoolAmount
	}
	return nil
}

func (x *GlpAsset) GetWeight() []byte {
	if x != nil {
		return x.Weight
	}
	return nil
}

func (x *GlpAsset) GetUsdgAmount() []byte {
	if x != nil {
		return x.UsdgAmount
	}
	return nil
}

func (x *GlpAsset) GetAllocation() []byte {
	if x != nil {
		return x.Allocation
	}
	return nil
}

var File_glp_proto protoreflect.FileDescriptor

var file_glp_proto_rawDesc = []byte{
	0x0a, 0x09, 0x67, 0x6c, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x67, 0x6c, 0x70,
	0x22, 0x15, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x47, 0x6c, 0x70, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3d, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x47, 0x6c,
	0x70, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x25, 0x0a, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x67, 0x6c, 0x70, 0x2e, 0x47, 0x6c, 0x70, 0x41, 0x73, 0x73, 0x65, 0x74, 0x52, 0x06,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x22, 0x9a, 0x01, 0x0a, 0x08, 0x47, 0x6c, 0x70, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x70,
	0x6f, 0x6f, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0a, 0x70, 0x6f, 0x6f, 0x6c, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x77,
	0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x77, 0x65, 0x69,
	0x67, 0x68, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x73, 0x64, 0x67, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x75, 0x73, 0x64, 0x67, 0x41, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x32, 0x53, 0x0a, 0x0a, 0x47, 0x6c, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x45, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x47, 0x6c, 0x70, 0x41, 0x73, 0x73, 0x65, 0x74,
	0x73, 0x12, 0x18, 0x2e, 0x67, 0x6c, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x6c, 0x70, 0x41, 0x73,
	0x73, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x67, 0x6c,
	0x70, 0x2e, 0x47, 0x65, 0x74, 0x47, 0x6c, 0x70, 0x41, 0x73, 0x73, 0x65, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_glp_proto_rawDescOnce sync.Once
	file_glp_proto_rawDescData = file_glp_proto_rawDesc
)

func file_glp_proto_rawDescGZIP() []byte {
	file_glp_proto_rawDescOnce.Do(func() {
		file_glp_proto_rawDescData = protoimpl.X.CompressGZIP(file_glp_proto_rawDescData)
	})
	return file_glp_proto_rawDescData
}

var file_glp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_glp_proto_goTypes = []interface{}{
	(*GetGlpAssetsRequest)(nil),  // 0: glp.GetGlpAssetsRequest
	(*GetGlpAssetsResponse)(nil), // 1: glp.GetGlpAssetsResponse
	(*GlpAsset)(nil),             // 2: glp.GlpAsset
}
var file_glp_proto_depIdxs = []int32{
	2, // 0: glp.GetGlpAssetsResponse.assets:type_name -> glp.GlpAsset
	0, // 1: glp.GlpService.GetGlpAssets:input_type -> glp.GetGlpAssetsRequest
	1, // 2: glp.GlpService.GetGlpAssets:output_type -> glp.GetGlpAssetsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_glp_proto_init() }
func file_glp_proto_init() {
	if File_glp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_glp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGlpAssetsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_glp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetGlpAssetsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_glp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlpAsset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_glp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_glp_proto_goTypes,
		DependencyIndexes: file_glp_proto_depIdxs,
		MessageInfos:      file_glp_proto_msgTypes,
	}.Build()
	File_glp_proto = out.File
	file_glp_proto_rawDesc = nil
	file_glp_proto_goTypes = nil
	file_glp_proto_depIdxs = nil
}
